/*

 SPRITETILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 0 to 8

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define spriteTilesBank 0

/* Super Gameboy palette 0 */
#define spriteTilesSGBPal0c0 6076
#define spriteTilesSGBPal0c1 8935
#define spriteTilesSGBPal0c2 6596
#define spriteTilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define spriteTilesSGBPal1c0 6076
#define spriteTilesSGBPal1c1 8935
#define spriteTilesSGBPal1c2 6596
#define spriteTilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define spriteTilesSGBPal2c0 6076
#define spriteTilesSGBPal2c1 8935
#define spriteTilesSGBPal2c2 6596
#define spriteTilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define spriteTilesSGBPal3c0 6076
#define spriteTilesSGBPal3c1 8935
#define spriteTilesSGBPal3c2 6596
#define spriteTilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define spriteTilesCGBPal0c0 6076
#define spriteTilesCGBPal0c1 276
#define spriteTilesCGBPal0c2 27200
#define spriteTilesCGBPal0c3 3171

/* Gameboy Color palette 1 */
#define spriteTilesCGBPal1c0 6076
#define spriteTilesCGBPal1c1 8935
#define spriteTilesCGBPal1c2 6596
#define spriteTilesCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define spriteTilesCGBPal2c0 6076
#define spriteTilesCGBPal2c1 8935
#define spriteTilesCGBPal2c2 6596
#define spriteTilesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define spriteTilesCGBPal3c0 6076
#define spriteTilesCGBPal3c1 8935
#define spriteTilesCGBPal3c2 6596
#define spriteTilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define spriteTilesCGBPal4c0 6076
#define spriteTilesCGBPal4c1 8935
#define spriteTilesCGBPal4c2 6596
#define spriteTilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define spriteTilesCGBPal5c0 6076
#define spriteTilesCGBPal5c1 8935
#define spriteTilesCGBPal5c2 6596
#define spriteTilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define spriteTilesCGBPal6c0 6076
#define spriteTilesCGBPal6c1 8935
#define spriteTilesCGBPal6c2 6596
#define spriteTilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define spriteTilesCGBPal7c0 6076
#define spriteTilesCGBPal7c1 8935
#define spriteTilesCGBPal7c2 6596
#define spriteTilesCGBPal7c3 5344

/* CGB palette entries. */
#define spriteTilesCGB0 0
#define spriteTilesCGB1 0
#define spriteTilesCGB2 0
#define spriteTilesCGB3 0
#define spriteTilesCGB4 0
#define spriteTilesCGB5 0
#define spriteTilesCGB6 0
#define spriteTilesCGB7 0
#define spriteTilesCGB8 0
/* Start of tile array. */
extern unsigned char spriteTiles[];

/* End of SPRITETILES.H */
